package com.peterlopusan.traveldiary.models.country

import com.google.gson.annotations.SerializedName
import com.peterlopusan.traveldiary.utils.TranslateApiManager
import com.squareup.moshi.Json

data class Country(
    var name: CountryName?,
    @Json(name = "cca2") @SerializedName("cca2") val shortname2: String?,
    @Json(name = "cca3") @SerializedName("cca3") val shortname3: String?,
    val capital: MutableList<String>?,
    val region: String?,
    val subregion: String?,
    val languages: Language?,
    val translations: CountryTranslations?,
    val latlng: MutableList<Double>?,
    val flag: String?,
    @Json(name = "idd") @SerializedName("idd") val callNumber: CallNumber?,
    val maps: CountryMap?,
    val independent: Boolean?,
    val population: Long?,
    val landlocked: Boolean?,
    val continents: MutableList<String>?,
    val flags: CountryImages?,
    val coatOfArms: CountryImages?,
    val currencies: Currencies?,
    val capitalInfo: CountryCapitalInfo,
    val timezones: MutableList<String>?
)

data class CountryName(
    val common: String?,
    val official: String?,
    var nativeName: CountryNativeName?
)

data class CountryTranslations(
    val slk: CountryName?,
    var eng: CountryName?
)

data class CountryMap(
    val googleMaps: String?
)

data class CountryImages(
    val png: String?,
    val svg: String?
)

data class CountryCapitalInfo(
    val latlng: MutableList<Double>?
)

data class CallNumber(
    val root: String?,
    val suffixes: MutableList<String>?
) {
    fun getCallNumbers(): MutableList<String> {
        val list = mutableListOf<String>()
        suffixes?.forEach {
            list.add(root+it)
        }

        return list
    }
}

data class CountryNativeName(
    val ron: CountryName?,
    val eng: CountryName?,
    val nau: CountryName?,
    val sqi: CountryName?,
    val niu: CountryName?,
    val pau: CountryName?,
    val som: CountryName?,
    val msa: CountryName?,
    val mlg: CountryName?,
    val ber: CountryName?,
    val mey: CountryName?,
    val ell: CountryName?,
    val gle: CountryName?,
    val grn: CountryName?,
    val sin: CountryName?,
    val tam: CountryName?,
    val afr: CountryName?,
    val nbl: CountryName?,
    val nso: CountryName?,
    val sot: CountryName?,
    val ssw: CountryName?,
    val tsn: CountryName?,
    val tso: CountryName?,
    val ven: CountryName?,
    val xho: CountryName?,
    val zul: CountryName?,
    val cal: CountryName?,
    val cha: CountryName?,
    val kin: CountryName?,
    val tvl: CountryName?,
    val nep: CountryName?,
    val bar: CountryName?,
    val nfr: CountryName?,
    val sag: CountryName?,
    val fij: CountryName?,
    val hif: CountryName?,
    val nno: CountryName?,
    val nob: CountryName?,
    val smi: CountryName?,
    val lav: CountryName?,
    val kaz: CountryName?,
    val tuk: CountryName?,
    val bul: CountryName?,
    val smo: CountryName?,
    val tkl: CountryName?,
    val dzo: CountryName?,
    val aze: CountryName?,
    val swa: CountryName?,
    val mlt: CountryName?,
    val de: CountryName?,
    val pap: CountryName?,
    val uzb: CountryName?,
    val mkd: CountryName?,
    val ukr: CountryName?,
    val bos: CountryName?,
    val fas: CountryName?,
    val tir: CountryName?,
    val lit: CountryName?,
    val pov: CountryName?,
    val fil: CountryName?,
    val bis: CountryName?,
    val aym: CountryName?,
    val que: CountryName?,
    val khm: CountryName?,
    val bwg: CountryName?,
    val kck: CountryName?,
    val khi: CountryName?,
    val ndc: CountryName?,
    val nde: CountryName?,
    val nya: CountryName?,
    val nrf: CountryName?,
    val kir: CountryName?,
    val hye: CountryName?,
    val cnr: CountryName?,
    val kal: CountryName?,
    val hmo: CountryName?,
    val tpi: CountryName?,
    val hin: CountryName?,
    val mon: CountryName?,
    val mya: CountryName?,
    val nor: CountryName?,
    val bel: CountryName?,
    val gsw: CountryName?,
    val roh: CountryName?,
    val kon: CountryName?,
    val lin: CountryName?,
    val dan: CountryName?,
    val ltz: CountryName?,
    val fao: CountryName?,
    val ton: CountryName?,
    val lat: CountryName?,
    val run: CountryName?,
    val mah: CountryName?,
    val glv: CountryName?,
    val hat: CountryName?,
    val prs: CountryName?,
    val pus: CountryName?,
    val heb: CountryName?,
    val pih: CountryName?,
    val rar: CountryName?,
    val lao: CountryName?,
    val gil: CountryName?,
    val cat: CountryName?,
    val eus: CountryName?,
    val glc: CountryName?,
    val jam: CountryName?,
    val crs: CountryName?,
    val amh: CountryName?,
    val ben: CountryName?,
    val mri: CountryName?,
    val nzs: CountryName?,
    val zdj: CountryName?,
    val bjz: CountryName?,
    val isl: CountryName?,
    val tgk: CountryName?,
    val her: CountryName?,
    val hgm: CountryName?,
    val kwn: CountryName?,
    val loz: CountryName?,
    val ndo: CountryName?,
    val tet: CountryName?,
    val mfe: CountryName?,
    val div: CountryName?,
    val ind: CountryName?,
    val lua: CountryName?,
    val vie: CountryName?,
    val kat: CountryName?,
    val arc: CountryName?,
    val ckb: CountryName?,
    val ara: CountryName?,
    val tha: CountryName?,
    val slv: CountryName?,
    val bre: CountryName?,
    val ces: CountryName?,
    val cym: CountryName?,
    val deu: CountryName?,
    val est: CountryName?,
    val fin: CountryName?,
    val fra: CountryName?,
    val hrv: CountryName?,
    val hun: CountryName?,
    val ita: CountryName?,
    val jpn: CountryName?,
    val kor: CountryName?,
    val nld: CountryName?,
    val per: CountryName?,
    val pol: CountryName?,
    val por: CountryName?,
    val rus: CountryName?,
    val slk: CountryName?,
    val spa: CountryName?,
    val srp: CountryName?,
    val swe: CountryName?,
    val tur: CountryName?,
    val urd: CountryName?,
    val zho: CountryName?
) {
    fun getNativeCountryName(): MutableList<CountryName> {
        val list = mutableListOf<CountryName>()
        val language = this::class.java.declaredFields

        for (field in language) {
            field.isAccessible = true
            val value = field.get(this) as? CountryName
            value?.let { list.add(it) }
        }

        return list

    }
}

data class Language(
    val ron: String?,
    val eng: String?,
    val nau: String?,
    val sqi: String?,
    val niu: String?,
    val pau: String?,
    val som: String?,
    val msa: String?,
    val mlg: String?,
    val ber: String?,
    val mey: String?,
    val ell: String?,
    val gle: String?,
    val grn: String?,
    val sin: String?,
    val tam: String?,
    val afr: String?,
    val nbl: String?,
    val nso: String?,
    val sot: String?,
    val ssw: String?,
    val tsn: String?,
    val tso: String?,
    val ven: String?,
    val xho: String?,
    val zul: String?,
    val cal: String?,
    val cha: String?,
    val kin: String?,
    val tvl: String?,
    val nep: String?,
    val bar: String?,
    val nfr: String?,
    val sag: String?,
    val fij: String?,
    val hif: String?,
    val nno: String?,
    val nob: String?,
    val smi: String?,
    val lav: String?,
    val kaz: String?,
    val tuk: String?,
    val bul: String?,
    val smo: String?,
    val tkl: String?,
    val dzo: String?,
    val aze: String?,
    val swa: String?,
    val mlt: String?,
    val de: String?,
    val pap: String?,
    val uzb: String?,
    val mkd: String?,
    val ukr: String?,
    val bos: String?,
    val fas: String?,
    val tir: String?,
    val lit: String?,
    val pov: String?,
    val fil: String?,
    val bis: String?,
    val aym: String?,
    val que: String?,
    val khm: String?,
    val bwg: String?,
    val kck: String?,
    val khi: String?,
    val ndc: String?,
    val nde: String?,
    val nya: String?,
    val nrf: String?,
    val kir: String?,
    val hye: String?,
    val cnr: String?,
    val kal: String?,
    val hmo: String?,
    val tpi: String?,
    val hin: String?,
    val mon: String?,
    val mya: String?,
    val nor: String?,
    val bel: String?,
    val gsw: String?,
    val roh: String?,
    val kon: String?,
    val lin: String?,
    val dan: String?,
    val ltz: String?,
    val fao: String?,
    val ton: String?,
    val lat: String?,
    val run: String?,
    val mah: String?,
    val glv: String?,
    val hat: String?,
    val prs: String?,
    val pus: String?,
    val heb: String?,
    val pih: String?,
    val rar: String?,
    val lao: String?,
    val gil: String?,
    val cat: String?,
    val eus: String?,
    val glc: String?,
    val jam: String?,
    val crs: String?,
    val amh: String?,
    val ben: String?,
    val mri: String?,
    val nzs: String?,
    val zdj: String?,
    val bjz: String?,
    val isl: String?,
    val tgk: String?,
    val her: String?,
    val hgm: String?,
    val kwn: String?,
    val loz: String?,
    val ndo: String?,
    val tet: String?,
    val mfe: String?,
    val div: String?,
    val ind: String?,
    val lua: String?,
    val vie: String?,
    val kat: String?,
    val arc: String?,
    val ckb: String?,
    val ara: String?,
    val tha: String?,
    val slv: String?,
    val bre: String?,
    val ces: String?,
    val cym: String?,
    val deu: String?,
    val est: String?,
    val fin: String?,
    val fra: String?,
    val hrv: String?,
    val hun: String?,
    val ita: String?,
    val jpn: String?,
    val kor: String?,
    val nld: String?,
    val per: String?,
    val pol: String?,
    val por: String?,
    val rus: String?,
    val slk: String?,
    val spa: String?,
    val srp: String?,
    val swe: String?,
    val tur: String?,
    val urd: String?,
    val zho: String?
) {
    fun getLanguage(): MutableList<String> {
        val list = mutableListOf<String>()
        val language = this::class.java.declaredFields

        for (field in language) {
            field.isAccessible = true
            val value = field.get(this) as? String
            TranslateApiManager().translateLanguage(value)?.let { list.add(it) }
        }

        return list
    }
}

data class CurrenciesInfo(
    val name: String?,
    val symbol: String?
)

data class Currencies(
    @Json(name = "EUR") @SerializedName("EUR") val eur: CurrenciesInfo?,
    @Json(name = "MDL") @SerializedName("MDL") val mdl: CurrenciesInfo?,
    @Json(name = "USD") @SerializedName("USD") val usd: CurrenciesInfo?,
    @Json(name = "AUD") @SerializedName("AUD") val aud: CurrenciesInfo?,
    @Json(name = "MZN") @SerializedName("MZN") val mzn: CurrenciesInfo?,
    @Json(name = "BRL") @SerializedName("BRL") val brl: CurrenciesInfo?,
    @Json(name = "XAF") @SerializedName("XAF") val xaf: CurrenciesInfo?,
    @Json(name = "CVE") @SerializedName("CVE") val cve: CurrenciesInfo?,
    @Json(name = "ALL") @SerializedName("ALL") val all: CurrenciesInfo?,
    @Json(name = "NZD") @SerializedName("NZD") val nzd: CurrenciesInfo?,
    @Json(name = "NGN") @SerializedName("NGN") val ngn: CurrenciesInfo?,
    @Json(name = "GMD") @SerializedName("GMD") val gmd: CurrenciesInfo?,
    @Json(name = "SOS") @SerializedName("SOS") val sos: CurrenciesInfo?,
    @Json(name = "YER") @SerializedName("YER") val yer: CurrenciesInfo?,
    @Json(name = "MYR") @SerializedName("MYR") val myr: CurrenciesInfo?,
    @Json(name = "XCD") @SerializedName("XCD") val xcd: CurrenciesInfo?,
    @Json(name = "GBP") @SerializedName("GBP") val gbp: CurrenciesInfo?,
    @Json(name = "MGA") @SerializedName("MGA") val mga: CurrenciesInfo?,
    @Json(name = "DZD") @SerializedName("DZD") val dzd: CurrenciesInfo?,
    @Json(name = "PYG") @SerializedName("PYG") val pyg: CurrenciesInfo?,
    @Json(name = "LKR") @SerializedName("LKR") val lkr: CurrenciesInfo?,
    @Json(name = "ZAR") @SerializedName("ZAR") val zar: CurrenciesInfo?,
    @Json(name = "KWD") @SerializedName("KWD") val kwd: CurrenciesInfo?,
    @Json(name = "SLL") @SerializedName("SLL") val sll: CurrenciesInfo?,
    @Json(name = "RWF") @SerializedName("RWF") val rwf: CurrenciesInfo?,
    @Json(name = "SYP") @SerializedName("SYP") val syp: CurrenciesInfo?,
    @Json(name = "HNL") @SerializedName("HNL") val hnl: CurrenciesInfo?,
    @Json(name = "JOD") @SerializedName("JOD") val jod: CurrenciesInfo?,
    @Json(name = "NPR") @SerializedName("NPR") val npr: CurrenciesInfo?,
    @Json(name = "LRD") @SerializedName("LRD") val lrd: CurrenciesInfo?,
    @Json(name = "MRU") @SerializedName("MRU") val mru: CurrenciesInfo?,
    @Json(name = "DJF") @SerializedName("DJF") val djf: CurrenciesInfo?,
    @Json(name = "FJD") @SerializedName("FJD") val fjd: CurrenciesInfo?,
    @Json(name = "NOK") @SerializedName("NOK") val nok: CurrenciesInfo?,
    @Json(name = "FKP") @SerializedName("FKP") val fkp: CurrenciesInfo?,
    @Json(name = "KZT") @SerializedName("KZT") val kzt: CurrenciesInfo?,
    @Json(name = "TMT") @SerializedName("TMT") val tmt: CurrenciesInfo?,
    @Json(name = "BGN") @SerializedName("BGN") val bgn: CurrenciesInfo?,
    @Json(name = "XPF") @SerializedName("XPF") val xpf: CurrenciesInfo?,
    @Json(name = "BBD") @SerializedName("BBD") val bbd: CurrenciesInfo?,
    @Json(name = "STN") @SerializedName("STN") val stn: CurrenciesInfo?,
    @Json(name = "BND") @SerializedName("BND") val bnd: CurrenciesInfo?,
    @Json(name = "BTN") @SerializedName("BTN") val btn: CurrenciesInfo?,
    @Json(name = "ARS") @SerializedName("ARS") val ars: CurrenciesInfo?,
    @Json(name = "AZN") @SerializedName("AZN") val azn: CurrenciesInfo?,
    @Json(name = "MXN") @SerializedName("MXN") val mxn: CurrenciesInfo?,
    @Json(name = "MAD") @SerializedName("MAD") val mad: CurrenciesInfo?,
    @Json(name = "GTQ") @SerializedName("GTQ") val gtq: CurrenciesInfo?,
    @Json(name = "KES") @SerializedName("KES") val kes: CurrenciesInfo?,
    @Json(name = "CZK") @SerializedName("CZK") val czk: CurrenciesInfo?,
    @Json(name = "GIP") @SerializedName("GIP") val gip: CurrenciesInfo?,
    @Json(name = "AWG") @SerializedName("AWG") val awg: CurrenciesInfo?,
    @Json(name = "AED") @SerializedName("AED") val aed: CurrenciesInfo?,
    @Json(name = "SSP") @SerializedName("SSP") val ssp: CurrenciesInfo?,
    @Json(name = "XOF") @SerializedName("XOF") val xof: CurrenciesInfo?,
    @Json(name = "SHP") @SerializedName("SHP") val shp: CurrenciesInfo?,
    @Json(name = "BWP") @SerializedName("BWP") val bwp: CurrenciesInfo?,
    @Json(name = "UZS") @SerializedName("UZS") val uzs: CurrenciesInfo?,
    @Json(name = "TND") @SerializedName("TND") val tnd: CurrenciesInfo?,
    @Json(name = "HKD") @SerializedName("HKD") val hkd: CurrenciesInfo?,
    @Json(name = "MKD") @SerializedName("MKD") val mkd: CurrenciesInfo?,
    @Json(name = "SRD") @SerializedName("SRD") val srd: CurrenciesInfo?,
    @Json(name = "SBD") @SerializedName("SBD") val sbd: CurrenciesInfo?,
    @Json(name = "UAH") @SerializedName("UAH") val uah: CurrenciesInfo?,
    @Json(name = "BAM") @SerializedName("BAM") val bam: CurrenciesInfo?,
    @Json(name = "IRR") @SerializedName("IRR") val irr: CurrenciesInfo?,
    @Json(name = "CUC") @SerializedName("CUC") val cuc: CurrenciesInfo?,
    @Json(name = "ERN") @SerializedName("ERN") val ern: CurrenciesInfo?,
    @Json(name = "PHP") @SerializedName("PHP") val php: CurrenciesInfo?,
    @Json(name = "TRY") @SerializedName("TRY") val try1: CurrenciesInfo?,
    @Json(name = "VUV") @SerializedName("VUV") val vuv: CurrenciesInfo?,
    @Json(name = "BOB") @SerializedName("BOB") val bob: CurrenciesInfo?,
    @Json(name = "RON") @SerializedName("RON") val ron: CurrenciesInfo?,
    @Json(name = "KHR") @SerializedName("KHR") val khr: CurrenciesInfo?,
    @Json(name = "ZWL") @SerializedName("ZWL") val zwl: CurrenciesInfo?,
    @Json(name = "KGS") @SerializedName("KGS") val kgs: CurrenciesInfo?,
    @Json(name = "GYD") @SerializedName("GYD") val gyd: CurrenciesInfo?,
    @Json(name = "AMD") @SerializedName("AMD") val amd: CurrenciesInfo?,
    @Json(name = "LBP") @SerializedName("LBP") val lbp: CurrenciesInfo?,
    @Json(name = "DKK") @SerializedName("DKK") val dkk: CurrenciesInfo?,
    @Json(name = "PGK") @SerializedName("PGK") val pgk: CurrenciesInfo?,
    @Json(name = "ZMW") @SerializedName("ZMW") val zmw: CurrenciesInfo?,
    @Json(name = "TTD") @SerializedName("TTD") val ttd: CurrenciesInfo?,
    @Json(name = "PEN") @SerializedName("PEN") val pen: CurrenciesInfo?,
    @Json(name = "SEK") @SerializedName("SEK") val sek: CurrenciesInfo?,
    @Json(name = "SDG") @SerializedName("SDG") val sdg: CurrenciesInfo?,
    @Json(name = "OMR") @SerializedName("OMR") val omr: CurrenciesInfo?,
    @Json(name = "INR") @SerializedName("INR") val inr: CurrenciesInfo?,
    @Json(name = "TWD") @SerializedName("TWD") val twd: CurrenciesInfo?,
    @Json(name = "MNT") @SerializedName("MNT") val mnt: CurrenciesInfo?,
    @Json(name = "TZS") @SerializedName("TZS") val tzs: CurrenciesInfo?,
    @Json(name = "CAD") @SerializedName("CAD") val cad: CurrenciesInfo?,
    @Json(name = "CRC") @SerializedName("CRC") val crc: CurrenciesInfo?,
    @Json(name = "CNY") @SerializedName("CNY") val cny: CurrenciesInfo?,
    @Json(name = "COP") @SerializedName("COP") val cop: CurrenciesInfo?,
    @Json(name = "MMK") @SerializedName("MMK") val mmk: CurrenciesInfo?,
    @Json(name = "RUB") @SerializedName("RUB") val rub: CurrenciesInfo?,
    @Json(name = "KPW") @SerializedName("KPW") val kpw: CurrenciesInfo?,
    @Json(name = "KYD") @SerializedName("KYD") val kyd: CurrenciesInfo?,
    @Json(name = "BYN") @SerializedName("BYN") val byn: CurrenciesInfo?,
    @Json(name = "SZL") @SerializedName("SZL") val szl: CurrenciesInfo?,
    @Json(name = "PLN") @SerializedName("PLN") val pln: CurrenciesInfo?,
    @Json(name = "CHF") @SerializedName("CHF") val chf: CurrenciesInfo?,
    @Json(name = "VES") @SerializedName("VES") val ves: CurrenciesInfo?,
    @Json(name = "PAB") @SerializedName("PAB") val pab: CurrenciesInfo?,
    @Json(name = "WST") @SerializedName("WST") val wst: CurrenciesInfo?,
    @Json(name = "THB") @SerializedName("THB") val thb: CurrenciesInfo?,
    @Json(name = "BSD") @SerializedName("BSD") val bsd: CurrenciesInfo?,
    @Json(name = "TOP") @SerializedName("TOP") val top: CurrenciesInfo?,
    @Json(name = "BIF") @SerializedName("BIF") val bif: CurrenciesInfo?,
    @Json(name = "BHD") @SerializedName("BHD") val bhd: CurrenciesInfo?,
    @Json(name = "HTG") @SerializedName("HTG") val htg: CurrenciesInfo?,
    @Json(name = "AFN") @SerializedName("AFN") val afn: CurrenciesInfo?,
    @Json(name = "ILS") @SerializedName("ILS") val ils: CurrenciesInfo?,
    @Json(name = "LYD") @SerializedName("LYD") val lyd: CurrenciesInfo?,
    @Json(name = "UYU") @SerializedName("UYU") val uyd: CurrenciesInfo?,
    @Json(name = "NIO") @SerializedName("NIO") val nio: CurrenciesInfo?,
    @Json(name = "CKD") @SerializedName("CKD") val ckd: CurrenciesInfo?,
    @Json(name = "LAK") @SerializedName("LAK") val lak: CurrenciesInfo?,
    @Json(name = "ANG") @SerializedName("ANG") val ang: CurrenciesInfo?,
    @Json(name = "JMD") @SerializedName("JMD") val jmd: CurrenciesInfo?,
    @Json(name = "EGP") @SerializedName("EGP") val egp: CurrenciesInfo?,
    @Json(name = "CLP") @SerializedName("CLP") val clp: CurrenciesInfo?,
    @Json(name = "LSL") @SerializedName("LSL") val lsl: CurrenciesInfo?,
    @Json(name = "GHS") @SerializedName("GHS") val ghs: CurrenciesInfo?,
    @Json(name = "SCR") @SerializedName("SCR") val scr: CurrenciesInfo?,
    @Json(name = "AOA") @SerializedName("AOA") val aoa: CurrenciesInfo?,
    @Json(name = "BMD") @SerializedName("BMD") val bmd: CurrenciesInfo?,
    @Json(name = "PKR") @SerializedName("PKR") val pkr: CurrenciesInfo?,
    @Json(name = "SAR") @SerializedName("SAR") val sar: CurrenciesInfo?,
    @Json(name = "KRW") @SerializedName("KRW") val krw: CurrenciesInfo?,
    @Json(name = "ETB") @SerializedName("ETB") val etb: CurrenciesInfo?,
    @Json(name = "BDT") @SerializedName("BDT") val bdt: CurrenciesInfo?,
    @Json(name = "KMF") @SerializedName("KMF") val kmf: CurrenciesInfo?,
    @Json(name = "BZD") @SerializedName("BZD") val bzd: CurrenciesInfo?,
    @Json(name = "UGX") @SerializedName("UGX") val ugx: CurrenciesInfo?,
    @Json(name = "SGD") @SerializedName("SGD") val sgd: CurrenciesInfo?,
    @Json(name = "HUF") @SerializedName("HUF") val huf: CurrenciesInfo?,
    @Json(name = "ISK") @SerializedName("ISK") val isk: CurrenciesInfo?,
    @Json(name = "TJS") @SerializedName("TJS") val tjs: CurrenciesInfo?,
    @Json(name = "NAD") @SerializedName("NAD") val nad: CurrenciesInfo?,
    @Json(name = "RSD") @SerializedName("RSD") val rsd: CurrenciesInfo?,
    @Json(name = "MUR") @SerializedName("MUR") val mur: CurrenciesInfo?,
    @Json(name = "MOP") @SerializedName("MOP") val mop: CurrenciesInfo?,
    @Json(name = "MVR") @SerializedName("MVR") val mvr: CurrenciesInfo?,
    @Json(name = "IDR") @SerializedName("IDR") val idr: CurrenciesInfo?,
    @Json(name = "CDF") @SerializedName("CDF") val cdf: CurrenciesInfo?,
    @Json(name = "VND") @SerializedName("VND") val vnd: CurrenciesInfo?,
    @Json(name = "GNF") @SerializedName("GNF") val gnf: CurrenciesInfo?,
    @Json(name = "GEL") @SerializedName("GEL") val gel: CurrenciesInfo?,
    @Json(name = "MWK") @SerializedName("MWK") val mwk: CurrenciesInfo?,
    @Json(name = "IQD") @SerializedName("IQD") val iqd: CurrenciesInfo?,
    @Json(name = "JPY") @SerializedName("JPY") val jpy: CurrenciesInfo?,
    @Json(name = "DOP") @SerializedName("DOP") val dop: CurrenciesInfo?,
    @Json(name = "QAR") @SerializedName("QAR") val qar: CurrenciesInfo?
) {
    fun getCurrencyInfo(): MutableList<CurrenciesInfo> {
        val list = mutableListOf<CurrenciesInfo>()
        val language = this::class.java.declaredFields

        for (field in language) {
            field.isAccessible = true

            val value = field.get(this) as? CurrenciesInfo
            value?.let { list.add(it) }
        }

        return list
    }
}

